Add XVFB_DISPLAY_LIMIT config v.0.11.1

diff --git a/utils/xvfb-run b/utils/xvfb-run
--- a/utils/xvfb-run
+++ b/utils/xvfb-run
@@ -1,9 +1,14 @@
 #!/bin/bash
 
 # allow settings to be updated via environment
+
+if [ -z $XVFB_DISPLAY_LIMIT ]; then
+  exit 2; # configuration error
+fi
+
 : "${xvfb_lockdir:=$HOME/.xvfb-locks}"
 : "${xvfb_display_min:=99}"
-: "${xvfb_display_max:=599}"
+: "${xvfb_display_max:=$XVFB_DISPLAY_LIMIT + 99}"
 
 # assuming only one user will use this, let's put the locks in our own home directory
 # avoids vulnerability to symlink attacks.
@@ -12,7 +17,11 @@ mkdir -p -- "$xvfb_lockdir" || exit
 i=$xvfb_display_min     # minimum display number
 while (( i < xvfb_display_max )); do
   if [ -f "/tmp/.X$i-lock" ]; then                # still avoid an obvious open display
-    (( ++i )); continue
+    (( ++i )); 
+    if (( i == xvfb_display_max )); then
+      exit 3; # every displays are busy
+    fi
+    continue
   fi
   exec 5>"$xvfb_lockdir/$i" || continue           # open a lockfile
   if flock -x -n 5; then                          # try to lock it
@@ -20,3 +29,4 @@ while (( i < xvfb_display_max )); do
   fi
   (( i++ ))
 done
+
